{
  "formatVersion": "1.1",
  "component": {
    "group": "dokka",
    "module": "dokka-json",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "dsog3c4e45cvhi2rxtnrtgptuu"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokka-json-0.1.jar",
          "url": "dokka-json-0.1.jar",
          "size": 43333,
          "sha512": "0b718154cff8ed1c16be2feca58e204130d950eea88dd95f865594f6b7838fb9b2354d3a3dd5b9ef4931c707803ede89d4b73c4d6d8a68c6ce07a3f409b76899",
          "sha256": "cf7f2ee2c8b182f50bce4b7643360db5fd92e08accab005adea83d8a216d84df",
          "sha1": "bf07a29b0c791a3b24fd1e1842c2c75426243990",
          "md5": "2412c1d89cd38e0c28d8f3ce3ca80684"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "1.4.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokka-json-0.1.jar",
          "url": "dokka-json-0.1.jar",
          "size": 43333,
          "sha512": "0b718154cff8ed1c16be2feca58e204130d950eea88dd95f865594f6b7838fb9b2354d3a3dd5b9ef4931c707803ede89d4b73c4d6d8a68c6ce07a3f409b76899",
          "sha256": "cf7f2ee2c8b182f50bce4b7643360db5fd92e08accab005adea83d8a216d84df",
          "sha1": "bf07a29b0c791a3b24fd1e1842c2c75426243990",
          "md5": "2412c1d89cd38e0c28d8f3ce3ca80684"
        }
      ]
    }
  ]
}
