{
  "formatVersion": "1.1",
  "component": {
    "group": "play",
    "module": "play-modular-code",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "play-modular-code-0.1.jar",
          "url": "play-modular-code-0.1.jar",
          "size": 16842,
          "sha512": "ffea52171543cdfa2f964abaf02407637cd1f14c3784e2e0159a70cb77ded5d2d573b06833a0aa80efff28aa042bc87f3bf98b0fd44b4494b7b322123ed7274e",
          "sha256": "8aa1f229b8ae8e920c0766ce17bab1b924da9681cb29cc731d0980ddcbaff051",
          "sha1": "2d605df3e1022940c6d7320dde977388cd29ae5f",
          "md5": "b78cd8024609f8ae234231ed21fc14e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "play-modular-code-0.1.jar",
          "url": "play-modular-code-0.1.jar",
          "size": 16842,
          "sha512": "ffea52171543cdfa2f964abaf02407637cd1f14c3784e2e0159a70cb77ded5d2d573b06833a0aa80efff28aa042bc87f3bf98b0fd44b4494b7b322123ed7274e",
          "sha256": "8aa1f229b8ae8e920c0766ce17bab1b924da9681cb29cc731d0980ddcbaff051",
          "sha1": "2d605df3e1022940c6d7320dde977388cd29ae5f",
          "md5": "b78cd8024609f8ae234231ed21fc14e0"
        }
      ]
    }
  ]
}
