// Code generated by Wire protocol buffer compiler, do not edit.
// Source: play.DoubleListValue in play.proto
package play

import com.squareup.wire.*
import com.squareup.wire.Syntax.PROTO_3
import okio.ByteString
import org.eclipse.collections.api.factory.primitive.DoubleLists
import org.eclipse.collections.api.list.primitive.DoubleList
import org.eclipse.collectionx.asJava
import org.eclipse.collectionx.ofList
import play.wire.PlayProtoAdapter

public class DoubleListValue(
  value: DoubleList = DoubleLists.immutable.empty(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DoubleListValue, Nothing>(ADAPTER, unknownFields) {

  constructor(
    value: List<Double> = emptyList(),
    unknownFields: ByteString = ByteString.EMPTY
  ) : this(DoubleLists.immutable.ofList(value), unknownFields)

  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.PACKED,
    declaredName = "value",
  )
  public val value: DoubleList = value.toImmutable()

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing =
    throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DoubleListValue) return false
    if (unknownFields != other.unknownFields) return false
    if (value != other.value) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + value.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (value.notEmpty()) result += """value_=$value"""
    return result.joinToString(prefix = "DoubleListValue{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value: List<Double> = this.value.asJava(), unknownFields: ByteString =
      this.unknownFields
  ): DoubleListValue = DoubleListValue(value, unknownFields)

  public companion object {
    @JvmStatic
    val EMPTY = DoubleListValue(DoubleLists.immutable.empty())

    @JvmField
    public val ADAPTER: ProtoAdapter<DoubleListValue> = object : ProtoAdapter<DoubleListValue>(
      FieldEncoding.LENGTH_DELIMITED,
      DoubleListValue::class,
      "type.googleapis.com/play.DoubleListValue",
      PROTO_3,
      null,
      "play.proto"
    ) {
      public override fun encodedSize(`value`: DoubleListValue): Int {
        var size = value.unknownFields.size
        size += PlayProtoAdapter.DOUBLE.asPacked().encodedSizeWithTag(1, value.value.asJava())
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: DoubleListValue): Unit {
        PlayProtoAdapter.DOUBLE.asPacked().encodeWithTag(writer, 1, value.value.asJava())
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: DoubleListValue): Unit {
        writer.writeBytes(value.unknownFields)
        PlayProtoAdapter.DOUBLE.asPacked().encodeWithTag(writer, 1, value.value.asJava())
      }

      public override fun decode(reader: ProtoReader): DoubleListValue {
        val value = DoubleLists.mutable.empty().asJava()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value.add(PlayProtoAdapter.DOUBLE.decodeAsDouble(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return DoubleListValue(
          value = value,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: DoubleListValue): DoubleListValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
