// Code generated by Wire protocol buffer compiler, do not edit.
// Source: play.LongListValue in play.proto
package play

import com.squareup.wire.*
import com.squareup.wire.Syntax.PROTO_3
import okio.ByteString
import org.eclipse.collections.api.factory.primitive.LongLists
import org.eclipse.collections.api.list.primitive.LongList
import org.eclipse.collectionx.asJava
import org.eclipse.collectionx.ofList
import play.wire.PlayProtoAdapter

public class LongListValue(
  value: LongList = LongLists.immutable.empty(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LongListValue, Nothing>(ADAPTER, unknownFields) {
  constructor(
    value: List<Long> = emptyList(),
    unknownFields: ByteString = ByteString.EMPTY
  ) : this(LongLists.immutable.ofList(value), unknownFields)

  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.PACKED,
    declaredName = "value",
  )
  public val value: LongList = value.toImmutable()

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing =
    throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LongListValue) return false
    if (unknownFields != other.unknownFields) return false
    if (value != other.value) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + value.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (value.notEmpty()) result += """value_=$value"""
    return result.joinToString(prefix = "LongListValue{", separator = ", ", postfix = "}")
  }

  public fun copy(value: LongList = this.value, unknownFields: ByteString = this.unknownFields):
    LongListValue = LongListValue(value, unknownFields)

  public companion object {

    @JvmStatic
    val EMPTY = LongListValue(LongLists.immutable.empty())

    @JvmField
    public val ADAPTER: ProtoAdapter<LongListValue> = object : ProtoAdapter<LongListValue>(
      FieldEncoding.LENGTH_DELIMITED,
      LongListValue::class,
      "type.googleapis.com/play.LongListValue",
      PROTO_3,
      null,
      "play.proto"
    ) {
      public override fun encodedSize(`value`: LongListValue): Int {
        var size = value.unknownFields.size
        size += PlayProtoAdapter.INT64.asPacked().encodedSizeWithTag(1, value.value.asJava())
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: LongListValue): Unit {
        PlayProtoAdapter.INT64.asPacked().encodeWithTag(writer, 1, value.value.asJava())
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: LongListValue): Unit {
        writer.writeBytes(value.unknownFields)
        PlayProtoAdapter.INT64.asPacked().encodeWithTag(writer, 1, value.value.asJava())
      }

      public override fun decode(reader: ProtoReader): LongListValue {
        val value_ = mutableListOf<Long>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_.add(PlayProtoAdapter.INT64.decodeAsLong(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return LongListValue(
          value = value_,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: LongListValue): LongListValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
