// Code generated by Wire protocol buffer compiler, do not edit.
// Source: play.LongLongMapValue in play.proto
package play

import com.squareup.wire.*
import com.squareup.wire.Syntax.PROTO_3
import okio.ByteString
import org.eclipse.collections.api.factory.primitive.LongLongMaps
import org.eclipse.collections.api.map.primitive.LongLongMap
import org.eclipse.collectionx.asJava
import org.eclipse.collectionx.ofAll

public class LongLongMapValue(
  value: LongLongMap = LongLongMaps.immutable.empty(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LongLongMapValue, Nothing>(ADAPTER, unknownFields) {

  constructor(
    value: Map<Long, Long> = emptyMap(),
    unknownFields: ByteString = ByteString.EMPTY
  ) : this(LongLongMaps.immutable.ofAll(value), unknownFields)

  @field:WireField(
    tag = 1,
    keyAdapter = "com.squareup.wire.ProtoAdapter#INT64",
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    declaredName = "value",
  )
  public val value: LongLongMap = value.toImmutable()

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing =
    throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LongLongMapValue) return false
    if (unknownFields != other.unknownFields) return false
    if (value != other.value) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + value.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (value.notEmpty()) result += """value_=$value"""
    return result.joinToString(prefix = "LongLongMapValue{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value: LongLongMap = this.value, unknownFields: ByteString =
      this.unknownFields
  ): LongLongMapValue = LongLongMapValue(value, unknownFields)

  public companion object {

    @JvmStatic
    val EMPTY = LongLongMapValue(LongLongMaps.immutable.empty())

    @JvmField
    public val ADAPTER: ProtoAdapter<LongLongMapValue> = object : ProtoAdapter<LongLongMapValue>(
      FieldEncoding.LENGTH_DELIMITED,
      LongLongMapValue::class,
      "type.googleapis.com/play.LongLongMapValue",
      PROTO_3,
      null,
      "play.proto"
    ) {
      private val valueAdapter: ProtoAdapter<Map<Long, Long>> by lazy {
        ProtoAdapter.newMapAdapter(ProtoAdapter.INT64, ProtoAdapter.INT64)
      }

      public override fun encodedSize(`value`: LongLongMapValue): Int {
        var size = value.unknownFields.size
        size += valueAdapter.encodedSizeWithTag(1, value.value.asJava())
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: LongLongMapValue): Unit {
        valueAdapter.encodeWithTag(writer, 1, value.value.asJava())
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: LongLongMapValue): Unit {
        writer.writeBytes(value.unknownFields)
        valueAdapter.encodeWithTag(writer, 1, value.value.asJava())
      }

      public override fun decode(reader: ProtoReader): LongLongMapValue {
        val value = LongLongMaps.mutable.empty()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> valueAdapter.decode(reader).forEach(value::put)
            else -> reader.readUnknownField(tag)
          }
        }
        return LongLongMapValue(
          value = value,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: LongLongMapValue): LongLongMapValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
